title:              O Meu Blog
email:              jorge.fernandes@ama.gov.pt
description:        Um tema da Start Bootstrap
author:             Jorge Fernandes
baseurl:            "/bootstrap-blog-jekyll"
url:                "https://jorgeponto.github.io"
# idioma principal do sítio Web
lang:                pt-PT

# Social Profiles
twitter_username:   SBootstrap
github_username:    StartBootstrap
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
